### ISSUE TITLE
Failed to correctly render first page

### ISSUE THREAD

**Issue by pedro93** [izuzak/atom-pdf-view#102]
Hi, I am using atom to write a latex document, however the very frontpage does not seem to be rendered in the pdf viewer. Using the default previewer in my mac the file output is as expected. 

The atom previewer: 

![screen shot 2015-12-31 at 18 13 07](https://cloud.githubusercontent.com/assets/3718654/12066569/3f7fcb62-afea-11e5-8ec6-b76bb4e69426.png)

vs my previewer:

![screen shot 2015-12-31 at 18 13 35](https://cloud.githubusercontent.com/assets/3718654/12066571/4707e4f0-afea-11e5-8495-118df8177900.png)

No errors or warnings are given.

**Comment by izuzak** [comment]
Can you upload that PDF somewhere and link to it here? It's kind of hard to investigate anything with nothing to go on, as I'm sure you understand. Also, you haven't mentioned which version of Atom you're using, which version of this package, which version of OS you're running, and whether this affect any other files (generated from latex or not). Providing more details would be helpful.

**Comment by izuzak** [comment]
Happy to reopen the issue once you provide more information :v:

**Comment by pedro93** [comment]
Thanks for looking into this!

As requested here is the information:
Pdf file - https://feupload.fe.up.pt/get/1cG14LYWo67DEY8
Atom version: 1.3.2
OS version: OS X Yosemite (10.10.5)

This issue was only detected after generating the pdf from the latex code, though I have rendered a few other latex projects and this is first time it happened. Haven't found this issue with any other pdf files.
Happy to provide any additional information if need be.

**Comment by izuzak** [comment]
Thanks! I'm seeing that problem as well -- reopening so that I can close it with a pull request which should fix things.

**Comment by izuzak** [comment]
So, it seems that the first page was triggering some behavior in the pdf.js library which needs to dynamically evaluate code. That's not allowed in Atom by default, so a workaround needs to be used (in the form of the "loophole" library). Couldn't get that to work in the version of pdf.js that was being used for some reason, so I ended up upgrading to a new version of pdf.js which caused new problems. After some jiggery-pokery -- I _think_ this should work now and nothing should be broken.

I've published a new version just now -- can you give it a try and see if things are working for you?

**Comment by pedro93** [comment]
Just updated the package, the following Atom log was given:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.10.5
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.38.0


### Stack Trace

Uncaught Error: Unknown action from worker: ready

```
At /Users/pedrosilva/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:236

Error: Unknown action from worker: ready
    at error (/Users/pedrosilva/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:236:9)
    at Worker.messageHandlerComObjOnMessage (/Users/pedrosilva/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:1525:7)
```

### Commands

```
     -1:07.3.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -0:05.5.0 latex:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "sublime-default-syntax"
    ],
    "disabledPackages": [
      "double-click-tree-view",
      "metrics"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "tree-view"
    ]
  },
  "pdf-view": {}
}
```

### Installed Packages

```coffee
# User
auto-indent, v0.5.0
autohide-tree-view, v0.25.1
build, v0.52.0
emmet, v2.3.17
language-latex, v0.6.1
latex, v0.28.2
linter, v1.11.3
pdf-view, v0.38.0
project-manager, v2.6.5
sublime-default-syntax, v0.2.7
sync-settings, v0.6.0
tab-close-double-click, v1.0.1

# Dev
No dev packages
```

**Comment by izuzak** [comment]
Strange -- I'm not seeing that. Can you describe what _exactly_ you did to trigger that error? Starting from the moment you opened Atom? Do you see that error when you just open other PDF files?

**Comment by pedro93** [comment]
I had to restart Atom, it seems to be working. Thank you very much for fixing this :pray:

**Comment by izuzak** [comment]
Ahh, great :D :sweat_smile: Thanks for letting me know.
