### ISSUE TITLE
Uncaught Error: Unknown action from worker: ready

### ISSUE THREAD

**Issue by gbouchar** [izuzak/atom-pdf-view#104]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.1
**Thrown From**: [pdf-view](https://github.com/izuzak/atom-pdf-view) package, v0.38.0

### Stack Trace

Uncaught Error: Unknown action from worker: ready

```
At /Users/gbouchar/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:236

Error: Unknown action from worker: ready
    at error (/Users/gbouchar/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:236:9)
    at Worker.messageHandlerComObjOnMessage (/Users/gbouchar/.atom/packages/pdf-view/node_modules/pdfjs-dist/build/pdf.js:1525:7)
```

### Commands

```
     -6:51.4.0 tabs:split-up (li.tab.sortable.right-clicked)
     -6:35.8.0 tabs:split-right (li.tab.sortable.active.right-clicked)
     -5:46.7.0 pane:split-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -5:20.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -1:01.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -1:01.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "pdf-view": {}
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latex-plus, v0.7.8
pdf-view, v0.38.0
vim-mode, v0.64.0

# Dev
No dev packages
```

**Comment by BDMorrell** [comment]
I got about this same message, although I attribute it to maybe not having much RAM left? (I'm trying to figure out how to reproduce the RAM issues of #72 well.)

**Comment by izuzak** [comment]
@gbouchar @BDMorrell This should go away after you restart Atom. I think it's a side-effect of the new version due to some changes in the underlying pdf.js library. Can you try restarting Atom and let me know if you can still reproduce this? Thanks!

**Comment by gbouchar** [comment]
thanks!
