### ISSUE TITLE
Forward search in SyncTeX not working

### ISSUE THREAD

**Issue by edwinksl** [izuzak/atom-pdf-view#107]
I was trying out the `latex` and `pdf-view` packages and noticed that forward search (from editor to PDF)  in SyncTex does not work, although reverse search (from PDF to editor) does work wonderfully.

**Comment by izuzak** [comment]
Just to make sure I understand -- can you clarify what "forward search (from editor to PDF)" and "reverse search (from PDF to editor)" means? The SyncTeX integration does one thing: when you click on something in the PDF, it brings you to the relevant line in the source file. There's no search involved. Did you perhaps expect that when you click a line in the source file -- the PDF would scroll to show the relevant part for that line?

**Comment by edwinksl** [comment]
Yeah, I expected that clicking a line in the source file would bring me to the relevant part in the PDF.

P.S.: "Forward search" and "reverse/inverse search" do sound confusing, but unfortunately that's how they are commonly called; see https://www.gnu.org/software/auctex/manual/auctex/I_002fO-Correlation.html for example.

**Comment by izuzak** [comment]
> Yeah, I expected that clicking a line in the source file would bring me to the relevant part in the PDF.

That would be a neat feature, but it's currently expected that it doesn't happen. Added the enhancement label on this issue. :v: Thanks for confirming

**Comment by dpo** [comment]
:+1:

**Comment by hmarthinsen** [comment]
That would be very useful.

**Comment by schlichtanders** [comment]
+1
it would be awesome to have such a fully interactive latex-preview within atom

**Comment by izuzak** [comment]
I'm going to reopen this. #111 added one half of support for this. @nsaje will probably followup with a PR to atom-latex soon to get the other part in as well. 

@nsaje if you don't have time for that -- can you add a comment here so that someone else might tackle it? :pray: Also, please let us know when that support lands in atom-latex so that we can close this. :v:

**Comment by nsaje** [comment]
The [PR](https://github.com/thomasjo/atom-latex/pull/170) has landed in atom-latex so the full functionality is now available to users that have both packages installed :+1:

**Comment by izuzak** [comment]
:sparkling_heart: @nsaje Thanks so much for your work -- I'm closing this now. :sparkler:
