### ISSUE TITLE
atom-pdf-view should remember position in pdf file on reload

### ISSUE THREAD

**Issue by hmarthinsen** [izuzak/atom-pdf-view#108]
I use pdf-view with LaTeX documents, and it works pretty well. However, whenever I recompile the pdf file (which I do a lot), pdf-view reloads the file and displays the *first* page. It is annoying that I have to manually scroll back to the position I was on before recompiling. Please make pdf-view remember the current position when it needs to reload.

**Comment by izuzak** [comment]
Thanks for the suggestion -- this sounds like a duplicate of https://github.com/izuzak/atom-pdf-view/issues/13 so I'm closing this one. I won't have time to work on this in the near future, but if you'd like to contribute -- I'd be happy to review a pull request.
