### ISSUE TITLE
Proposal: Change synctex "single click" behavior

### ISSUE THREAD

**Issue by sherwoodinc** [izuzak/atom-pdf-view#110]
Hi,

I found that having the mouse single click take you to the latex source is a bit of a problem.
Many times I want to just focus the pdf-view window to scroll with the keyboard, and if I click on the text with the mouse it navigates to a piece of code which is not important at the moment. In order to avoid this I'm forced to click on the tab title, which is a bit annoying.

I propose changing the "single click" to "double click" (perhaps with a single/double click configuration option defaulting to the former option)

Regards.

**Comment by izuzak** [comment]
Thanks for the feedback, @sherwoodinc :bow:

> I propose changing the "single click" to "double click" (perhaps with a single/double click configuration option defaulting to the former option)

I like this idea. :+1: I'd be happy to review a pull request if you'd like to work on this.

**Comment by sherwoodinc** [comment]
I'll try to look at the code.

**Comment by nsaje** [comment]
:+1:   , I also find it a bit annoying, when I only want to focus the tab.

**Comment by nsaje** [comment]
@sherwoodinc I'm also happy to contribute the code, if you're not already working on this?

**Comment by sherwoodinc** [comment]
By all means do. I couldn't take a look at this yet.
