### ISSUE TITLE
Add option to invert color scheme or add dark color scheme (night mode in acrobat viewer)

### ISSUE THREAD

**Issue by bryandebourbon** [izuzak/atom-pdf-view#113]
(feature request) the option to invert colors would be beneficial for night coding/reading and being consistent with atom's default color scheme

**Comment by pravin** [comment]
+1

**Comment by qubix12** [comment]
+1 It would be amazing to have this option, specially if you use some pdf document/book to learn to code, or as reference. Please add this one.

**Comment by Alexis-Martin** [comment]
+1

**Comment by huberfelix0** [comment]
+1

**Comment by m3adi3c** [comment]
+1 from me as well.

**Comment by pnjun** [comment]
+1 from me!

**Comment by jkerkhoff** [comment]
I could really use this, so I'll look into implementing it when I have time. Feel free to ping me if that doesn't happen within one month.

**Comment by aakhmetz** [comment]
+1

**Comment by MatteoLacki** [comment]
+1

**Comment by miketrexler** [comment]
I added a pull request for this Night Mode feature: https://github.com/izuzak/atom-pdf-view/pull/178. 

Checking the `Night Mode` setting will invert the colors 100%.

To customize your view a bit further, you can add the following to your Atom stylesheet:
```
.pdf-view {
  -webkit-filter: invert(88%) !important;
}
```

Personally I have found a value around 88% to be easiest on the eyes.

Thank you to @PeterNerlich for suggesting this solution: https://github.com/mozilla/pdf.js/issues/8253

**Comment by izuzak** [comment]
This was added in https://github.com/izuzak/atom-pdf-view/pull/178 -- there's now a night mode config option which does what was suggested in https://github.com/izuzak/atom-pdf-view/issues/113#issuecomment-300301272:

```
&.night-mode {
   -webkit-filter: invert(100%);
}
```

Thanks again to @miketrexler :bow:
