### ISSUE TITLE
Maintain scale to fit with pane resize 

### ISSUE THREAD

**Issue by OJFord** [izuzak/atom-pdf-view#119]
~~Would be great to have:
1. Command to scale to fit the PDF within pane
2. Option to trigger this scaling to fit as pane is resized~~

PR 112 (already linked below) scales the PDF to fit the pane on load. It would be great to have this automatic on pane resizing.

**Comment by izuzak** [comment]
Thanks for opening an issue, @OJFord. To keep things simple -- can you please open another issue for the second feature and use this issue only for the first one (please edit the issue title and body)? One issue per feature request or bug report makes it much easier to maintain and track things.

**Comment by OJFord** [comment]
Sorry about that. Went with item 2 for this issue, since in my opinion the PR above solves the same problem as item 1.

**Comment by cbrnr** [comment]
@OJFord but it would be nice to have a command "fit to width" so we can manually trigger this. There's no issue for this feature so I'll create one right now.

**Comment by OJFord** [comment]
I haven't used Atom for years and there's no other interest here; I'm struggling for context but it seems like the above merged PR addresses this 80% anyway, so, closing. 🙂
