### ISSUE TITLE
Scaling slow; occasionally rotates 180deg instead

### ISSUE THREAD

**Issue by OJFord** [izuzak/atom-pdf-view#120]
It takes several seconds to see any response to `CMD`-`-`, and sometimes it will flip the page upside down instead. This makes it difficult and time-consuming to zoom out enough to make the page fit on load.

**Comment by izuzak** [comment]
Thanks for opening an issue. :bow: I think the "occasionally rotates 180deg" part is covered by https://github.com/izuzak/atom-pdf-view/issues/109, so I'd like to ask you again to keep this issue focused on one thing, which seems to be performance. 

I think the zooming speed is related to the size of the file. It should be possible to improve that with some more intelligent tactics, but I don't expect to have time to look into this myself anytime soon. If you'd (or someone else) would like to open a pull request to improve this -- I'd be happy to review it.

**Comment by OJFord** [comment]
Whoops, sorry I didn't see the other issue.

Yes, I noticed more recently on opening a single page PDF that it was considerably faster. This will be somewhat mitigated by #112, since at least that's only waiting once, as opposed to the current setup which is scale -> wait -> check -> scale -> wait -> ...

I may have a look at some point, but to be honest I'm doubtful I'd be able to. No worries though, thanks for the time you do put in for this awesome package!

**Comment by OJFord** [comment]
Closing as I haven't used Atom for years, and nobody else has shown interest in this; so seems no reason to keep it open.
