### ISSUE TITLE
fitToWidthOnOpen only takes the width of the first page into account

### ISSUE THREAD

**Issue by 314eter** [izuzak/atom-pdf-view#124]
Pages with a larger width than the first page don't fit.

**Comment by izuzak** [comment]
> Pages with a larger width than the first page don't fit.

What exactly did you expect would happen in this case? Fit to the largest page in the document? How do other PDF viewers behave?

**Comment by 314eter** [comment]
I think using the largest page is the most logical thing to do. I just checked, and this is what evince does.
