### ISSUE TITLE
Object.TextEditor is deprecated.

### ISSUE THREAD

**Issue by thomasjo** [izuzak/atom-pdf-view#127]
This might only be live on Atom `master`, but regardless I just got the deprecation warning below.

---
The `TextEditor` constructor is no longer public.

To construct a text editor, use `atom.workspace.buildTextEditor()`.
To check if an object is a text editor, use `atom.workspace.isTextEditor(object)`.
```
Object.TextEditor (/Users/thomasjo/Code/atom/atom/exports/atom.coffee:39:14)
Object.<anonymous> (/Users/thomasjo/.atom/packages/pdf-view/lib/pdf-editor-view.js:25:27)
Module._compile (/Users/thomasjo/Code/atom/atom/src/native-compile-cache.js:103:30)
Object..js (/Users/thomasjo/Code/atom/atom/src/compile-cache.js:208:21)
Module.load (module.js:356:32)
Function._load (module.js:313:12)
```

**Comment by izuzak** [comment]
Thanks for opening an issue, @thomasjo :blue_heart:

**Comment by thomasjo** [comment]
@izuzak No worries! I should have opened a PR with a fix, just never got around to it :bow:
