### ISSUE TITLE
problem file

### ISSUE THREAD

**Issue by skilllet** [izuzak/atom-pdf-view#143]
[Malware Sample Sources for Researchers.pdf](https://github.com/izuzak/atom-pdf-view/files/361240/Malware.Sample.Sources.for.Researchers.pdf)

**Comment by izuzak** [comment]
Thanks for the file, but there's no need to create two issues. What I suggested was that you add this PDF in a comment on https://github.com/izuzak/atom-pdf-view/issues/142. I just reopened that issue.
