### ISSUE TITLE
Synctex reverse does not work on Atom 1.9.7

### ISSUE THREAD

**Issue by mcolmant** [izuzak/atom-pdf-view#145]
Hello,

I updated recently my Atom editor and the synctex reverse does not work anymore.
It works like a charm before this update.

Do you have the same problem?

Thanks,

**Comment by ig0774** [comment]
It works for me on 1.9.7 / OS X.

A few questions:

1. Do you have `pdf_file.pdf` and `pdf_file.synctex.gz` available and in the same folder?
1. Have you set the `syncTeXPath` setting? This is definitely necessary on OS X, likely necessary on Linux, and possibly helpful on Windows.
1. What OS and TeX distribution are you using? MiKTeX, for example, doesn't ship with a `synctex` binary.

**Comment by mcolmant** [comment]
Thanks for your reply.

The file is correctly generated and synctex is available in $PATH, but I did not set the path in the settings.
I'm working on OSX, with texlive.

**Comment by mcolmant** [comment]
You are right, it now works by setting the parameter ;-)
It worked before without setting it.

I can close the issue, thanks for your help!

**Comment by izuzak** [comment]
❤️ @ig0774 and @mcolmant for working together to resolve this!
