### ISSUE TITLE
package:pdf-view can not download

### ISSUE THREAD

**Issue by yinglish07** [izuzak/atom-pdf-view#147]
package:pdf-view can not download

**Comment by izuzak** [comment]
@yinglish07 Could you share more details about this problem? Which version of Atom are you using, which OS, is this the only package you're having trouble with, which error message are you seeing exactly, can you provide a screenshot? If you can provide more details, we can reopen this issue.

**Comment by yinglish07** [comment]
It's probably the problem of internet connect, and it has already been fixed.  Thanks for your replying.

________________________________
发件人: Ivan ?u?ak <notifications@github.com>
发送时间: 2016年8月13日 2:30
收件人: izuzak/atom-pdf-view
抄送: yinglish07; Mention
主题: Re: [izuzak/atom-pdf-view] package:pdf-view can not download (#147)


@yinglish07<https://github.com/yinglish07> Could you share more details about this problem? Which version of Atom are you using, which OS, is this the only package you're having trouble with, which error message are you seeing exactly, can you provide a screenshot? If you can provide more details, we can reopen this issue.

―
