### ISSUE TITLE
No status bar!

### ISSUE THREAD

**Issue by largrate** [izuzak/atom-pdf-view#150]
I had installed pdf-view in Atom so that I can compile .tex doc and view its result. It works well, but no status bar. So I can't jump to page. How to solve this problem? 
Thanks!
pdf-view version: 0.50.0
Atom: 1.9.9

**Comment by izuzak** [comment]
I see the status bar just fine on Atom 1.9.9 when I open a PDF. Perhaps some of your other packages are causing problems? Can you reproduce the problem with only pdf-view installed (and no other packages)? Does it happen for every PDF or only some? 

Also, you can jump to a page using a command: "Pdf View: Go To Page" from the command palette.

**Comment by largrate** [comment]
Thanks for your reply.
Today, when I launched Atom, the pdf-view works well. 
Thank you!
