### ISSUE TITLE
Add command "fit to width"

### ISSUE THREAD

**Issue by cbrnr** [izuzak/atom-pdf-view#153]
It would be nice to be able to fit a PDF document to the current width, i.e. there should be a command/shortcut for this. Currently, this happens only on load (if the corresponding setting is checked) as implemented in #112. Cf #119.

**Comment by PKAlbers** [comment]
+1
It would be useful to be able to resize the pane width and have the current width of the pdf view adjust (if if only on re-load).

**Comment by kkmann** [comment]
+1

**Comment by izuzak** [comment]
This was added via https://github.com/izuzak/atom-pdf-view/pull/206 🎉 Thanks again, @ngasoft :bow:
