### ISSUE TITLE
Synctex reverse sync: add option to choose which pane to use when opening tex files 

### ISSUE THREAD

**Issue by sherwoodinc** [izuzak/atom-pdf-view#159]
When using reverse sync in a project consisting of many tex files, unopened tex files get opened in the same pane of the PDF viewer.
This means that, each time this happens, I have to manually drag the newly opened tex file to the left pane where other tex files are open.

The best would be to have a drop down list letting you choose the pane. Alternatively, a simpler on/off option would be to use the left pane always.

**Comment by sherwoodinc** [comment]
I went ahead and implemented it myself.
I'm sending a pull request if you like the change.

**Comment by izuzak** [comment]
Implemented in https://github.com/izuzak/atom-pdf-view/pull/160 🎉
