### ISSUE TITLE
Multiple reloads on latexmk

### ISSUE THREAD

**Issue by guyhoffman** [izuzak/atom-pdf-view#166]
Every time you compile a LaTeX file with latexmk, it results in 3-5 (slow) refreshes of the pdf-view window. Is that something that can be addressed? Thanks for your hard work!

**Comment by izuzak** [comment]
Thanks for opening an issue :bow: -- this seems like a duplicate of https://github.com/izuzak/atom-pdf-view/issues/161 so I'm closing this in favor of that. :v:
