### ISSUE TITLE
Install fails when atom binary is not named "atom"

### ISSUE THREAD

**Issue by pobetiger** [izuzak/atom-pdf-view#17]
Attempt to install after v0.6.0 fails if atom is not named "atom" in the filesystem.

Upgrade will fail.

**Comment by stavpup** [comment]
Installing “pdf-view@0.14.0” failed.Hide output…

npm http GET https://registry.npmjs.org/pathwatcher
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/fs-plus
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Linux 3.13.0-44-generic
npm ERR! command "/opt/atom/resources/app/apm/node_modules/atom-package-manager/bin/node" "/opt/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/opt/atom/resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/stavros14/.atom/.apmrc" "install" "/home/stavros14/.atom/.node-gyp/.atom/.apm/pdf-view/0.14.0/package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd /tmp/apm-install-dir-115017-17401-1k24zzp
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/fs-plus
npm http 304 https://registry.npmjs.org/pathwatcher
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/apm-install-dir-115017-17401-1k24zzp/npm-debug.log
npm ERR! not ok code 0

**Comment by izuzak** [comment]
> npm ERR! Please check if you have git installed and in your PATH.

@stavpup do you have git installed and listed in your PATH? Seems like that's causing problems, based on the error output you provided.

**Comment by izuzak** [comment]
Closing this, but let me know if adding git to your PATH doesn't help.
