### ISSUE TITLE
Atom is crashing when used

### ISSUE THREAD

**Issue by aounleonardo** [izuzak/atom-pdf-view#174]
Working on a Windows 10

**Comment by izuzak** [comment]
Thanks for opening an issue, @aounleonardo, but it's very hard to provide any advice without any specific details. For example, which version of Atom are you using and which version of this package? Does Atom crash as soon as you start Atom or when you open a PDF? Can you reproduce the problem with only this package installed and no other packages? 

I'd be happy to reopen this once more information is provided.
