### ISSUE TITLE
Dependency `pdfjs-dist` needs to be updated

### ISSUE THREAD

**Issue by ppoffice** [izuzak/atom-pdf-view#179]
Dependency `pdfjs-dist` needs to be updated for some Chinese characters overlap with each other in the current version(pdfjs-dist@@1.6.264).

![qq 20170512084046](https://cloud.githubusercontent.com/assets/8849362/25977640/6afdde0e-36ef-11e7-9adb-92b1239d5993.png)

After updating to `pdfjs-dist@1.8.349`, this problem disappeared.

This is the PDF file in the above screenshot: [main.pdf](https://github.com/izuzak/atom-pdf-view/files/994755/main.pdf)

**Comment by izuzak** [comment]
Thanks for letting me know -- I just published a new version which has the latest pdfjs dependency. :+1:
