### ISSUE TITLE
Suggestion: Add command to toggle PDF source

### ISSUE THREAD

**Issue by Alhadis** [izuzak/atom-pdf-view#184]
AFAIK, it's currently impossible to display the PDF's source data without disabling this package... Would it be possible to have a "View Source" command, or something to that effect? It could easily be added to a context menu. =)

I don't predict there'll be too many Atom users who need to dig through PDF code, but hey...

**Comment by izuzak** [comment]
Hi @Alhadis 👋 

> Would it be possible to have a "View Source" command, or something to that effect? It could easily be added to a context menu. =)

I'm _guessing_ that would be possible. That said, I probably won't have time to work on this myself in the near future. If you or someone else would like to open a pull request to add this -- I'd be happy to review it.

**Comment by Alhadis** [comment]
I don't foresee it being any more complicated than adding a default `TextEditor`, which is what users see if 
they try opening a PDF without this package installed.

Nonetheless, I'm afraid I haven't the time to submit a PR for this (or else I would've already done so). Hence I'm bringing it up for another contributor to tackle, if they're so inclined. =)

**FYI:** I'm in the midst of a [realtime Troff renderer](https://github.com/Alhadis/Roff.js/blob/47d4eda/lib/postproc/canvas.js), and I was comparing its output with Groff's PDF output. Which is when I realised it'd be handy to switch the PDF view off. =)
