### ISSUE TITLE
Not automatically updating window

### ISSUE THREAD

**Issue by jprks** [izuzak/atom-pdf-view#196]
Hi,

The pdf viewer has recently stopped automatically updating as I compile the LaTeX document. In other words, when I compile the document it changes the pdf but the file it does not update the file in my atom window. I have to reopen the file to see the changes. The LaTeX file does not have any compilation errors. I have not changed any settings since it developed this problem. Please help me solve this issue. 

Thanks,
James

**Comment by izuzak** [comment]
Thanks for the report! I just published a new version of the package (v0.62.0) which should hopefully fix the problem. Try updating to the new version and let me know if it doesn't help! 🙏

**Comment by jprks** [comment]
Unfortunately, that did not work. The problem persists.

**Comment by izuzak** [comment]
Strange -- works fine for me.

Can you provide more information about your setup? You didn't provide any information about which version of the package you're using, which version of Atom, which OS, or what your configuration for the package looks like.

**Comment by jprks** [comment]
I am using the most up-to-date version of the package, as you suggested above, 0.62.0. Atom version 1.23.1. Windows 10 Education. I am not sure what configuration of the package I am using. Could you tell me how to figure that out for you?

**Comment by izuzak** [comment]
> I am not sure what configuration of the package I am using. Could you tell me how to figure that out for you?

Go to Atom -> Preferences -> Packages and then slick on "Settings" button for the pdf-view package.

<img width="884" alt="screen shot 2018-01-01 at 21 28 31" src="https://user-images.githubusercontent.com/38924/34470844-ca189d62-ef3a-11e7-80e2-5395b6dd93e3.png">


Send a screenshot of the settings you see there, like this

<img width="678" alt="screen shot 2018-01-01 at 21 29 18" src="https://user-images.githubusercontent.com/38924/34470849-da8fec04-ef3a-11e7-8f86-15fb09e803d5.png">

**Comment by jprks** [comment]
![snapshot_1](https://user-images.githubusercontent.com/20494147/34470860-df6945f4-ef08-11e7-9bb8-6b4f4f555e86.PNG)

**Comment by izuzak** [comment]
All of that looks okay to me. Not sure what might be causing problems for you -- sorry! You might try uninstalling and re-installing the package. Other than that, I'm out of ideas and I don't have Windows installed to see if it's something related to that. I have the same version of Atom, same version of the package, and the same config.

**Comment by jprks** [comment]
Ok, I'll try re-installing it. Thanks for the help anyway.
