### ISSUE TITLE
Can't load my pdf

### ISSUE THREAD

**Issue by Matows** [izuzak/atom-pdf-view#200]
Since I updated the package (less than an hour ago), when I try to load my pdf (generated with Latex) pdf-view show me the source code of the pdf : 
![pdf-view-fail](https://user-images.githubusercontent.com/22861912/35776927-937c944a-09a5-11e8-88b0-515aa5465c4c.png)
I don't reely now what you need. So I'll answer you asap
Simon.

**Comment by courier83** [comment]
I confirm the problem like @Matows with the last update.

**Comment by izuzak** [comment]
Thanks for reporting this so quickly, @Matows @courier83 :bow: 

I've reverted the latest changes and published a new version. Sorry for the trouble!

**Comment by courier83** [comment]
Working. Thanks.
