### ISSUE TITLE
Pdf-view does not display Chinese characters

### ISSUE THREAD

**Issue by bujianbusan** [izuzak/atom-pdf-view#207]
Pdf-view does not display Chinese characters

**Comment by izuzak** [comment]
@bujianbusan Thanks for opening an issue, but it would be great if you could provide a bit more information with reports like these. Can you share a PDF which isn't displaying correctly for you, and a screenshot of what you see? Also, which version of Atom, which OS+version, and which version of this package are you using?

**Comment by izuzak** [comment]
Closing since no additional information was provided. Happy to reopen if the information is provided in the future :v:
