### ISSUE TITLE
Bad performance, made Atom unresponsive

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [izuzak/atom-pdf-view#222]
Had to remove the package manually. 
I don't know if it had something to do with the folder my PDFs are contained 
in which were ~140 documents.

Almost crashed my whole system, high memory usage, > 5 gig for atom alone!

Can't use it unfortunately.

**Comment by izuzak** [comment]
Thanks for reporting this, @hp8wvvvgnj6asjm7 :bow:. Happy to reopen this and take a closer look when I have some free time if you can provide clear reproduction steps and information on which system you're using (which OS and version, which Atom version, which version of this package).

**Comment by hp8wvvvgnj6asjm7** [comment]
- Latest Atom Beta 
- Used normal Atom too.
- Win7 x64 ent

- 144 documents (450mb) in folder
- after opening and closing a few, the memory suddenly spikes up like mad until the whole operating system becomes almost unresponsive.

I attached the pdf file which crashes the app:

[(International Series on Microprocessor-Based and Intelligent Systems Engineering 23) John Harris (auth.) - An Introduction to Fuzzy Logic Applications-Springer Netherlands (2000).pdf](https://github.com/izuzak/atom-pdf-view/files/3009878/International.Series.on.Microprocessor-Based.and.Intelligent.Systems.Engineering.23.John.Harris.auth.-.An.Introduction.to.Fuzzy.Logic.Applications-Springer.Netherlands.2000.pdf)

**Comment by hp8wvvvgnj6asjm7** [comment]
I can confirm that the issues show up the moment i open the pdf file uploaded here. ^

**Comment by hp8wvvvgnj6asjm7** [comment]
> 
> 
> Thanks for reporting this, @hp8wvvvgnj6asjm7 bowing_man. Happy to reopen this and take a closer look when I have some free time if you can provide clear reproduction steps and information on which system you're using (which OS and version, which Atom version, which version of this package).

please reopen issue

**Comment by hp8wvvvgnj6asjm7** [comment]
@izuzak  pls reopen :D

**Comment by izuzak** [comment]
Thanks for those details, @hp8wvvvgnj6asjm7. 

There's no need to spam the issue with multiple comments and change the title of the issue to say REOPEN PLS. A single issue with the details I asked for would have been enough. 

As I mentioned before -- I probably won't have time to look into this, but if you would like to investigate and open a pull request to make the experience better -- please feel free. 👍

**Comment by hp8wvvvgnj6asjm7** [comment]
https://github.com/izuzak/atom-pdf-view/issues/135
