### ISSUE TITLE
Suggestion: Allow text highlighting

### ISSUE THREAD

**Issue by sbrl** [izuzak/atom-pdf-view#223]
PDF.js in Firefox allows you to highlight text in a PDF. It would be really cool if this package did too, as then I could copy and paste content from a PDF into another file. Currently, I have to open it in my system viewer to do this, which is rather a pain.

**Comment by izuzak** [comment]
Thanks for opening -- I think this is a duplicate of https://github.com/izuzak/atom-pdf-view/issues/7, so I'll close this out. Let me know if I misunderstood, though! 🍰

**Comment by sbrl** [comment]
Yep, this is a duplicate. I did search before opening an issue, but didn't find that one.
