### ISSUE TITLE
Window does not close

### ISSUE THREAD

**Issue by fippu** [izuzak/atom-pdf-view#227]
Assume you build a LaTeX file with `atom-latex` and then have it automatically open in the preview window powered by `pdf-view`.

Pressing `Shift+Cmd+W` should close that window, as should clicking File -- Close Window. However, nothing happens and the window stays open.

**Comment by izuzak** [comment]
@fippu Thanks for opening an issue. Just to make sure I understand -- are you able to reproduce this problem without using `atom-latex`? If so, can you post instructions for that here? If not, what makes you believe there's a problem with this package and it's not a problem with `atom-latex` or somewhere else?

**Comment by fippu** [comment]
@izuzak Those are good questions. As I have just started using atom, I am not sure. How can I open a PDF in `pdf-view` **in a new window**? When opened in a tab, there is no problem. So unless I find another way of opening a new PDF window, I do not know how to reproduce it without `atom-latex`.

What makes me believe this is a `pdf-view` problem is that I believe the window is opened and controlled by the PDF viewer. This might, of course, be due to my lack of deeper knowledge. If, instead, the window is somehow managed by `atom-latex`, the bug would be there.

**Comment by Aerijo** [comment]
@izuzak @fippu `atom-latex` does not use this package, it bundles the [example / default PDF.js viewer](https://github.com/ashthespy/Atom-LaTeX/tree/master/viewer).

**Comment by fippu** [comment]
@Aerijo  Thanks for the clarification. As a consequence, I will close the issue.
