### ISSUE TITLE
Blank PDF view pane 

### ISSUE THREAD

**Issue by WeilinDeng** [izuzak/atom-pdf-view#238]
I was able to succssfully compile the latex file and generate the pdf file. However, in the pdf-view pane, there is no pdf shown.

![image](https://user-images.githubusercontent.com/14908080/114639690-7499cd80-9c9c-11eb-9993-a6874efff491.png)

**Comment by xiangyulsu** [comment]
Same issue

**Comment by wdrz** [comment]
It happened to me as well

**Comment by Samisanerd** [comment]
I'm also having this issue

**Comment by pre77yg00d** [comment]
yup same here

**Comment by linusjanek** [comment]
same here

**Comment by oliviamcgleish** [comment]
Same here

**Comment by adahuabe** [comment]
same

**Comment by mkornejew** [comment]
Same here -- it worked perfectly fine yesterday 10 pm CET. 
Presumably, problems roots in latest Atom update (to version 1.56.0).

**Comment by linusjanek** [comment]
Does anyone here know of a short term solution, meaning a pdf-Viewer that can update the given pdf upon saving? Currently I'm reopening the given files in Acrobat over and over again but I feel like there has to be a more elegant way...

**Comment by ThisFungus** [comment]
> Does anyone here know of a short term solution, meaning a pdf-Viewer that can update the given pdf upon saving? Currently I'm reopening the given files in Acrobat over and over again but I feel like there has to be a more elegant way...

I can confirm that downgrade from Atom 1.56 to 1.55 hotfixed this issue.

**Comment by WeilinDeng** [comment]
> > Does anyone here know of a short term solution, meaning a pdf-Viewer that can update the given pdf upon saving? Currently I'm reopening the given files in Acrobat over and over again but I feel like there has to be a more elegant way...
> 
> I can confirm that downgrade from Atom 1.56 to 1.55 hotfixed this issue.

I tried to downgrade atom as you said and the issue disappear. It seems to be related an issue of pdf-view package with latest version of atom.

**Comment by linusjanek** [comment]
> > Does anyone here know of a short term solution, meaning a pdf-Viewer that can update the given pdf upon saving? Currently I'm reopening the given files in Acrobat over and over again but I feel like there has to be a more elegant way...
> 
> I can confirm that downgrade from Atom 1.56 to 1.55 hotfixed this issue.

Thanks!

**Comment by pre77yg00d** [comment]
how do you force Atom to not automatically update to 1.56?

**Comment by Homoe-hs** [comment]
same，waiting for fixing

**Comment by KosalaHerath** [comment]
Same with Version 1.56.0

**Comment by vBuresh** [comment]
Same (Atom v1.56.0, Debian 11)

**Comment by lvschenck** [comment]
Same for me after auto update to 1.56

**Comment by adahuabe** [comment]
> > > Does anyone here know of a short term solution, meaning a pdf-Viewer that can update the given pdf upon saving? Currently I'm reopening the given files in Acrobat over and over again but I feel like there has to be a more elegant way...
> > 
> > 
> > I can confirm that downgrade from Atom 1.56 to 1.55 hotfixed this issue.
> 
> I tried to downgrade atom as you said and the issue disappeared. It seems to be an issue of pdf-view package with latest version of atom.

Does anyone know how to downgrade Atom in Windows?

**Comment by pilotag** [comment]
Same issue :(0

**Comment by Homoe-hs** [comment]
> > > > Does anyone here know of a short term solution, meaning a pdf-Viewer that can update the given pdf upon saving? Currently I'm reopening the given files in Acrobat over and over again but I feel like there has to be a more elegant way...
> > > 
> > > 
> > > I can confirm that downgrade from Atom 1.56 to 1.55 hotfixed this issue.
> > 
> > 
> > I tried to downgrade atom as you said and the issue disappeared. It seems to be an issue of pdf-view package with latest version of atom.
> 
> Does anyone know how to downgrade Atom in Windows?

go to the  atom.io, in the "release note" you can find it

**Comment by rolshoven** [comment]
If you don't want to downgrade atom, you could do the same as me and temporarily open PDFs with the open-unsupported-files package.

**Comment by debanik09** [comment]
Any idea when a fix will be available. It's already 3 days since the bug was reported.

**Comment by MeindertHH** [comment]
Downgraded Atom to 1.55.0 (https://github.com/atom/atom/releases/tag/v1.55.0) and will wait updating until fixed.

**Comment by chrisv42** [comment]
same issue here

**Comment by maxgonzalezb** [comment]
same issue (Atom 1.56, Windows x64)

**Comment by kawano-takahiro** [comment]
For the time being, it seems that we need to downgrade it to fix this issue, but does anyone know when they can totally fix this kind of issue?

**Comment by ko-no-DIO-dawryyyy** [comment]
> I was able to succssfully compile the latex file and generate the pdf file. However, in the pdf-view pane, there is no pdf shown.
> 
> ![image](https://user-images.githubusercontent.com/14908080/114639690-7499cd80-9c9c-11eb-9993-a6874efff491.png)

i have the same issue but my teammate dosen't

**Comment by moritzpoll** [comment]
Same here. Anything we can do in terms of debugging we can help with? My console stays blank. Even external PDFs cannot be opened anymore for me.

**Comment by massimilianocomin** [comment]
Same issue here.

> `atom --version`
```
Atom    : 1.56.0
Electron: 9.4.4
Chrome  : 83.0.4103.122
Node    : 12.14.1
```


> `apm --version`
```
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.56.0
python 3.7.6
git 2.20.1
```

> `sw_vers`
```
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G6032
```

**Comment by WillBartee** [comment]
Same Issue

**Comment by majkee15** [comment]
I am experiencing the same issue.

**Comment by thomas40510** [comment]
Same for me! Atom version 1.56.0

**Comment by izuzak** [comment]
Hello, everyone! Sorry for not responding to this sooner

This package hasn't been changed in a while, so something changed in Atom recently which broke this package. I'm not really sure what that is and probably won't have time to look into it anytime soon due to personal reasons. With that in mind, downgrading Atom seems like a quick fix for folks who just want to continue working. A longer term solution would be for someone else to figure out what exactly changed in Atom that broke this package and then fix things (I'd be happy to review a pull request with a fix). An alternative is that you switch to some other Atom package for viewing PDFs, e.g. https://atom.io/packages/pdfjs-viewer or https://atom.io/packages/pdf-view-plus. 

Wish I had better news for you all, but I don't.

**Comment by KerDigital** [comment]
Thanks for your answer @izuzak 

For information pdf-view-plus has the same issue.

**Comment by KerDigital** [comment]
And same issue with pdfjs-viewer...

This is the error message I see : "Missing PDF file."

![2021-04-21_22-39-19](https://user-images.githubusercontent.com/63921832/115618030-6d08a300-a2f2-11eb-9d5f-7e5024e712a8.png)

**Comment by dsosa114** [comment]
Same issue. All packages based on PDFjs seem to have this problem.

**Comment by lionelmalletpro** [comment]
Hello every one, 
unfortunately, pdf-view-plus(  https://atom.io/packages/pdf-view-plus ) doesn't work either, since Atom's last update to version 1.56.1

**Comment by MeindertHH** [comment]
Thanks @izuzak.

**Comment by toadfarmer** [comment]
The solution I found was 
add this 
```
PDFJS.disableWorker = true;
```
at around line 16 of 
~/.atom/packages/pdf-view/lib/pdf-editor-view.js

**Comment by linusjanek** [comment]
> The solution I found was 
> add this 
> ```
> PDFJS.disableWorker = true;
> ```
> at around line 16 of 
> ~/.atom/packages/pdf-view/lib/pdf-editor-view.js

Worked for me also, thanks!

**Comment by KosalaHerath** [comment]
> The solution I found was
> add this
> 
> ```
> PDFJS.disableWorker = true;
> ```
> 
> at around line 16 of
> ~/.atom/packages/pdf-view/lib/pdf-editor-view.js

Worked for Windows 10  and macOS 11. Thank you!

**Comment by WeilinDeng** [comment]
Thanks to @toadfarmer for the fix!

**Comment by Tarun-Mahajan** [comment]
@toadfarmer Thanks a lot for the fix!

**Comment by mfhepp** [comment]
It also worked for me; please merge the pull request from https://github.com/izuzak/atom-pdf-view/pull/241

**Comment by mjrodgers** [comment]
Still having this issue with v 0.73, it displays properly if I generate a latex file and it automatically opens, but gives me a blank pane still if I double click on a pdf file to display it.

**Comment by aallca-p** [comment]
> Still having this issue with v 0.73, it displays properly if I generate a latex file and it automatically opens, but gives me a blank pane still if I double click on a pdf file from the tree explorer.

I too am having the same issue, even after updating just this morning. The above provided code is already present in "~/.atom/packages/pdf-view/lib/pdf-editor-view.js"
![image](https://user-images.githubusercontent.com/50245510/124355465-55497700-dbdf-11eb-94ee-42cf6134e40c.png)

**Comment by rithwikjc** [comment]
I am also having the issue reported by @mjrodgers 
When I build latex file, the pdf opens in a new pane as intended. But if I open any pdf from the tree, it is blank.
