### ISSUE TITLE
Module did not self-register

### ISSUE THREAD

**Issue by ccharlton** [izuzak/atom-pdf-view#42]
Version: PDF View 0.14.0
I'm seeing this in the error console:

```
pathwatcher@2.3.5
Error message: module did not self-register
```

**Comment by izuzak** [comment]
@ccharlton Which version of Atom are you using and which OS? Does this happen when you're installing the package or when you're using the package?

**Comment by izuzak** [comment]
Approach from https://github.com/izuzak/atom-pdf-view/issues/48 should help with this, but I would still love it if someone could reproduce the problem reliably.
