### ISSUE TITLE
Cannot install on Ubuntu 14.04 x64

### ISSUE THREAD

**Issue by matyasir** [izuzak/atom-pdf-view#51]
This is my output:

Installing “pdf-view@0.17.0” failed.Hide output…

> runas@2.0.0 install /tmp/apm-install-dir-11522-19394-163gwvj/node_modules/pdf-view/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild

make: Entering directory `/tmp/apm-install-dir-11522-19394-163gwvj/node_modules/pdf-view/node_modules/pathwatcher/node_modules/runas/build'
  CXX(target) Release/obj.target/runas/src/main.o
make: Leaving directory `/tmp/apm-install-dir-11522-19394-163gwvj/node_modules/pdf-view/node_modules/pathwatcher/node_modules/runas/build'

make: g++: Command not found
make: *** [Release/obj.target/runas/src/main.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/opt/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11522-19394-163gwvj/node_modules/pdf-view/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/robbie/.atom/.apm/.apmrc" "--userconfig" "/home/robbie/.atom/.apmrc" "install" "/tmp/d-11522-19394-1w5t8rm/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11522-19394-163gwvj/npm-debug.log

**Comment by izuzak** [comment]
> make: g++: Command not found
> make: *** [Release/obj.target/runas/src/main.o] Error 127

Do you have g++? Can you try installing it and see if it helps? See https://github.com/asciidoctor/atom-asciidoc-preview/issues/30 for a similar issue.
