### ISSUE TITLE
Go to page default shortcut

### ISSUE THREAD

**Issue by jorin-vogel** [izuzak/atom-pdf-view#74]
First, thank you for this nice plugin! 
Works nicely for me.

I saw the go-to-page feature and my first reaction was to hit _ctrl-g_ (as in go-to-line on OSX).
Don't know if it's just me or would this be a good default keybinding?

```coffeescript
'.pdf-view':
  'ctrl-g': 'pdf-view:go-to-page'
```

**Comment by izuzak** [comment]
Great idea -- just added it! Thanks! :zap:
