### ISSUE TITLE
Auto-refresh

### ISSUE THREAD

**Issue by SamuelMarks** [izuzak/atom-pdf-view#88]
At a glance this plugin is great! - Just one feature missing, auto reload/refresh PDF when it changes on disk.

My use-case is generating PDF from LaTeX documents.

Thanks

**Comment by izuzak** [comment]
> Just one feature missing, auto reload/refresh PDF when it changes on disk.

That works fine for me. I opened a PDF, then manually replaced it with a PDF with the same name but different content, and the PDF refreshed in Atom. Can you try doing the same and let me know if that doesn't work?

I'm guessing that you're hitting some case related to your configuration or how PDFs are generated. Would you mind sharing more details about your configuration (OS+version, Atom+version, pdf-view version) and how PDFs are generated? 

This package is used in https://github.com/thomasjo/atom-latex, and as far as I know -- it works for users of that package just fine.

**Comment by SamuelMarks** [comment]
Hmm, that's strange.

Anyway, in my project I've got some code generation going on, all automated with `make pdf`.

I'm on Ubuntu 15.04 x64 with Atom 1.0.19 and pdf view 0.30.0.

**Comment by izuzak** [comment]
> That works fine for me. I opened a PDF, then manually replaced it with a PDF with the same name but different content, and the PDF refreshed in Atom. Can you try doing the same and let me know if that doesn't work?

Have you tried doing this? Thanks.

**Comment by SamuelMarks** [comment]
Tried that, same issue (i.e.: new PDF isn't shown in the preview)

**Comment by izuzak** [comment]
> Tried that, same issue (i.e.: new PDF isn't shown in the preview)

I'm unable to reproduce this on Ubuntu 15.04 and Atom 1.0.19. See GIF below -- as soon as I replace the original PDF with a new one, the PDF refreshes in Atom with pdf-view:

![linux](https://cloud.githubusercontent.com/assets/38924/10564490/82e5246a-75b6-11e5-9ac8-dfad7a858f6d.gif)

Can you share a similar GIF which clearly demonstrates the problem?

**Comment by SamuelMarks** [comment]
Just tried again, for the first time since upgrading to your latest version, and it's now working

:+1:

**Comment by izuzak** [comment]
Yay, happy to hear that -- thanks for letting me know!
