### ISSUE TITLE
Filename should be quoted in SyncTeX -o option

### ISSUE THREAD

**Issue by xax** [izuzak/atom-pdf-view#91]
The filename should be quoted (might work cross platform) or escaped, when being passed to *SyncTeX* via the `-o page:x:y:file` option, otherwise e.g. path specifications containing a space make reverse sync fail.

This might happen in `onCanvasClick` regarding the variable `clickspec`.

**Comment by 50Wliu** [comment]
So this is probably why Synctex isn't working for me.  My PDF file has a space in it.

**Comment by izuzak** [comment]
Thanks for the report, @xax (and for the confirmation from @50Wliu)! I'd be happy to review a pull request if you'd like to submit one to fix this.

**Comment by l0calh05t** [comment]
I was testing on a different machine today, where synctex is NOT on the path and `synctexPath` is therefore set. On this system, paths with spaces work fine as `execFile` automatically takes care of quoting. For systems where `synctexPath` is not set, `exec` is used instead with a regular string. Is it possible to call a program that is on the path via `execFile` which is generally much safer?

**Comment by izuzak** [comment]
There's a new version now which has changes from https://github.com/izuzak/atom-pdf-view/issues/95 --  let me know if you can still reproduce the problem
