### ISSUE TITLE
Synctex does not appear to work (Windows)

### ISSUE THREAD

**Issue by l0calh05t** [izuzak/atom-pdf-view#93]
I installed the pdf-view and latex packages and built a pdf. The pdf is displayed correctly and a .synctex.gz file is generated. However, clicking the document has no effect.

**Comment by 50Wliu** [comment]
Does your filename have a space in it?

**Comment by izuzak** [comment]
Thanks for the hint, @50Wliu -- I'm going to assume this is the same problem as in https://github.com/izuzak/atom-pdf-view/issues/91. @l0calh05t -- if that's not the case, please let me know and provide more information.

**Comment by l0calh05t** [comment]
@50Wliu The filename does not, but the path does. Thanks for making that connection. All files I tried had a path with spaces in it.
