### ISSUE TITLE
synctex doesn't work in v0.35.0

### ISSUE THREAD

**Issue by X-G** [izuzak/atom-pdf-view#96]
Dear all,

I just update pdf-view of version 0.35.0. It seems that the synctex doesn't work anymore.
I'm using macos 10.11. 
In the setting page of pdf-view, I set the path of synctex `/usr/local/texlive/2015/bin/x86_64-darwin/synctex`.
It's works fine in the previous version of pdf-view.

**Comment by izuzak** [comment]
Thanks so much for the report! I just pushed a new version which should fix this. Let me know if you can still reproduce in 0.36.0.

**Comment by X-G** [comment]
It works fine.
Many thanks!! @izuzak .

**Comment by xax** [comment]
@izuzak Great! Works for me this way using `exec` as well as `execFile` running a Linux.
